### ISSUE TITLE
`wc -c` counts newlines

### ISSUE THREAD

**Issue by pjvandehaar** [lifthrasiir/rustlog#2]
(Sorry, I'm not sure where else to put this kind of comment.)

In your recent blogpost, you run

```
$ strings target/release/hello | wc
```

and then say

> 94339 printable bytes and 5893 zero bytes (one per line) make almost 100 KB.

But `wc -c` counts newlines.  Just try:

```
$ echo -e 'a\nb' | wc`
2    2    4
```

So, you only have 94 KB of strings plus NULLs.  Your point is still valid, but that part is confusing.

**Comment by lifthrasiir** [comment]
Ahaha, I must have been sleepy at that time. You are right, fixed the post. Thank you!
